### ISSUE TITLE
Feedback from testing

### ISSUE THREAD

**Issue by lnfernux** [securepractice/mailrisk-sentinel-connector#1]
Hey guys.

Some feedback from testing so far.

1. Add a keyvault to secure variables.

Easy to implement, just add a keyvault-block with secrets under resources, and refer to the same values in the input-variables. Then you can just refer to the secrets in the function. This allows the managed identity for the function to grab the secrets, but no one else.

**Example json-block for keyvault + secrets (apikey, apisecret, workspacekey):**

```json
{
		"type": "Microsoft.KeyVault/vaults",
		"apiVersion": "2016-10-01",
		"name": "[variables('KeyVaultName')]",
		"location": "[resourceGroup().location]",
		"dependsOn": [
	            "[resourceId('Microsoft.Web/sites', variables('FunctionName'))]"
		],
		"properties": {
	"sku": {
			"family": "A",
			"name": "Standard"
	},
	"tenantId": "[subscription().tenantId]",
	"accessPolicies": [
			{
		"tenantId": "[subscription().tenantId]",
		"objectId": "[reference(resourceId('Microsoft.Web/sites', variables('FunctionName')),'2019-08-01', 'full').identity.principalId]",
		"permissions": {
				"secrets": [ "get",
					          "list"
					]
		}
	    }
	],
	"enabledForDeployment": false,
	"enabledForDiskEncryption": false,
	"enabledForTemplateDeployment": true,
	"enableSoftDelete": true
		},
		"resources": [
	{
			"type": "secrets",
			"apiVersion": "2016-10-01",
			"name": "[variables('WorkspaceKey')]",
			"dependsOn": [
		            "[resourceId('Microsoft.KeyVault/vaults/', variables('KeyVaultName'))]"
			],
			"properties": {
		"value": "[parameters('WorkspaceKey')]",
		"contentType": "string",
		"attributes": {
				"enabled": true
		}
			}
	},
          {
			"type": "secrets",
			"apiVersion": "2016-10-01",
			"name": "[variables('APISecret')]",
			"dependsOn": [
		            "[resourceId('Microsoft.KeyVault/vaults/', variables('KeyVaultName'))]"
			],
			"properties": {
		"value": "[parameters('APISecret')]",
		"contentType": "string",
		"attributes": {
				"enabled": true
		}
			}
	},
	{
			"type": "secrets",
			"apiVersion": "2016-10-01",
			"name": "[variables('APISecret')]",
			"dependsOn": [
		              "[resourceId('Microsoft.KeyVault/vaults/', variables('KeyVaultName'))]"
			],
			"properties": {
		"value": "[parameters('APIKey')]",
		"contentType": "string",
		"attributes": {
				"enabled": true
		}
			}
	}
		]
}
```
**Example block for azure function config with dependencies on keyvault and references to secrets:**
```json
"resources": [
  {
      "apiVersion": "2018-11-01",
      "type": "config",
      "name": "appsettings",
      "dependsOn": [
          "[concat('Microsoft.Web/sites/', variables('FunctionName'))]",
          "[resourceId('Microsoft.KeyVault/vaults/', variables('KeyVaultName'))]",
	  "[resourceId('Microsoft.KeyVault/vaults/secrets', variables('KeyVaultName'), variables('APIKey'))]",            
	  "[resourceId('Microsoft.KeyVault/vaults/secrets', variables('KeyVaultName'), variables('APISecret'))]",
          "[resourceId('Microsoft.KeyVault/vaults/secrets', variables('KeyVaultName'), variables('WorkspaceKey'))]"
      ],
      "properties": {
          "FUNCTIONS_EXTENSION_VERSION": "~4",
          "FUNCTIONS_WORKER_RUNTIME": "python",
          "APPINSIGHTS_INSTRUMENTATIONKEY": "[reference(resourceId('Microsoft.insights/components', variables('FunctionName')), '2015-05-01').InstrumentationKey]",
          "APPLICATIONINSIGHTS_CONNECTION_STRING": "[reference(resourceId('microsoft.insights/components', variables('FunctionName')), '2015-05-01').ConnectionString]",
          "AzureWebJobsStorage": "[concat('DefaultEndpointsProtocol=https;AccountName=', toLower(variables('FunctionName')),';AccountKey=',listKeys(resourceId('Microsoft.Storage/storageAccounts', toLower(variables('FunctionName'))), '2019-06-01').keys[0].value, ';EndpointSuffix=',toLower(variables('StorageSuffix')))]",
          "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING": "[concat('DefaultEndpointsProtocol=https;AccountName=', toLower(variables('FunctionName')),';AccountKey=', listKeys(resourceId('Microsoft.Storage/storageAccounts', toLower(variables('FunctionName'))), '2019-06-01').keys[0].value, ';EndpointSuffix=',toLower(variables('StorageSuffix')))]",
          "WEBSITE_CONTENTSHARE": "[toLower(variables('FunctionName'))]",
          "WORKSPACE_ID": "[parameters('WorkspaceId')]",
          "WORKSPACE_KEY": "[concat('@Microsoft.KeyVault(SecretUri=', reference(variables('WorkspaceKey')).secretUriWithVersion, ')')]"
          "API_KEY": "[concat('@Microsoft.KeyVault(SecretUri=', reference(variables('APISecret')).secretUriWithVersion, ')')]"
          "API_SECRET": "[concat('@Microsoft.KeyVault(SecretUri=', reference(variables('APIKey')).secretUriWithVersion, ')')]"
          "logAnalyticsUri": "[variables('LogAnaltyicsUri')]",
          "BASE_URL": "https://api.test.mailrisk.net/v1/"
      }
  }
```

2. Include some guidance on how to scope for individual customers.

At the moment it's a bit unclear how to set up the API for usage if you manage multiple customers.
A solution to this would be the ability to enable the API for a single "tenant" (customer) and that also solves all filtering. I'm aware this is an MSSP issue, but would be great to have an easy solution to this.

3. API Secret/Key setup
At the moment we are testing this by creating a new user that we generate API-keys on. Is this the suggested way of doing it? If it is (or not), the connector will require some guidance steps in how to set up a user for API-usage with the data connector (best practice). Refer to SentinelOne and Qualys data connectors for some examples.

Other than this it looks to work. Will add more if I come across it.

**Comment by lnfernux** [comment]
Minor update:

It also seems that currently all new findings are duplicated, so each entry appears twice. Will keep an eye on this to see if it's consistent.

**Comment by ingin97** [comment]
@infernuxmonster 
1. Made a PR with changes proposed by you regarding the keyvault. If you have time, it would be nice if you could review it in order to avoid obvious mistakes.

**Comment by erlangsec** [comment]
Thanks for your helpful feedback and questions! As for partner access/filtering, I can understand that this is a bit unclear at the moment. While our API does support unified partner access to multiple tenants, we have currently not built support for this feature in this connector. It has been our understanding that Azure Sentinel/connector needs to be configured individually per end customer. Therefore, we have assumed that for each of these customers, it is worth creating an individual API user per customer in Secure Practice, so that in turn, a distinct API key will be used per customer/connector in Sentinel. Although using a common partner key for connectors across all customers, with filtering, could be maybe convenient, it is probably safer to constrain any customer based access to data with a customer specific key, rather than filtering after receiving the data. Does this make sense for your use case?

As for the duplicate entries, the events should be different, e.g. metadata_received and contents_received, according to the events diagram here: https://developer.securepractice.co/#events

**Comment by lnfernux** [comment]
Hey @erlangsec - that makes a ton of sense, was just wondering if that was the intended way (creating a new API-user for each customer), because you'd either need to integrate your SSO-provider with the customers "tenant" to create a email alias for the API user, or have the customer create one for you. Compare to something like Qualys, where you can create API-users without having to use email aliases, it's a lot less overhead.

But yeah, we will be creating one user for each customer to serve as the API-user there.

**Comment by erlangsec** [comment]
Yes, unfortunately we don't support creating API users without an email address today, sorry about that. For now, it can be a good idea to maintain one partner user (with email alias, however no actual mailbox is needed) per customer, so that the API key won't be disabled in case a personal admin user leaves the company and their user (with API access) is deleted. This same user can also be used for setting up Azure AD sync, which also requires an API key.
